namespace PokemonBattleSim
{
    #region Ability
    /// <summary>
    /// Represents the effects of all abilities
    /// </summary>
    public class Ability
    {
        string name;
        string desc;
        int id;

        public Ability(string n, string d, int id)
        {
            name = n;
            desc = d;
            this.id = id;
        }
    }
    #endregion

    #region Abilities
    public static class Abilities
    {
        #region Declarations
        #region A-H
        public static Ability Adaptabililty;
        public static Ability Aerilate;
        public static Ability Aftermath;
        public static Ability AirLock;
        public static Ability Analytic;
        public static Ability AngerPoint;
        public static Ability Anticipation;
        public static Ability ArenaTrap;
        public static Ability AromaVeil;
        public static Ability AuraBreak;
        public static Ability BadDreams;
        public static Ability Battery;
        public static Ability BattleArmor;
        public static Ability BattleBond;
        public static Ability BeastBoost;
        public static Ability Beserk;
        public static Ability BigPecks;
        public static Ability Blaze;
        public static Ability Bulletproof;
        public static Ability CheekPouch;
        public static Ability Chlorophyll;
        public static Ability ClearBody;
        public static Ability CloudNine;
        public static Ability ColorChange;
        public static Ability Comatose;
        public static Ability Competitive;
        public static Ability CompoundEyes;
        public static Ability Contrary;
        public static Ability Corrosion;
        public static Ability CursedBody;
        public static Ability CuteCharm;
        public static Ability Damp;
        public static Ability Dancer;
        public static Ability DarkAura;
        public static Ability Dazzling;
        public static Ability Defeatist;
        public static Ability Defiant;
        public static Ability DeltaStream;
        public static Ability DesolateLand;
        public static Ability Disguise;
        public static Ability Download;
        public static Ability Drizzle;
        public static Ability Drought;
        public static Ability DrySkin;
        public static Ability EarlyBird;
        public static Ability EffectSpore;
        public static Ability ElectricSurge;
        public static Ability EmergencyExit;
        public static Ability FairyAura;
        public static Ability Filter;
        public static Ability FlameBody;
        public static Ability FlareBoost;
        public static Ability FlashFire;
        public static Ability FlowerGift;
        public static Ability FlowerVeil;
        public static Ability Fluffy;
        public static Ability Forecast;
        public static Ability Forewarn;
        public static Ability FriendGuard;
        public static Ability Frisk;
        public static Ability FullMetalBody;
        public static Ability FurCoat;
        public static Ability GaleWings;
        public static Ability Galvanize;
        public static Ability Gluttony;
        public static Ability Gooey;
        public static Ability GrassPelt;
        public static Ability GrassySurge;
        public static Ability Guts;
        public static Ability Harvest;
        public static Ability Healer;
        public static Ability Heatproof;
        public static Ability HeavyMetal;
        public static Ability HoneyGather;
        public static Ability HugePower;
        public static Ability Hustle;
        public static Ability Hydration;
        public static Ability HyperCutter;
        #endregion
        #region I-R
        public static Ability IceBody;
        public static Ability Illuminate;
        public static Ability Illusion;
        public static Ability Immunity;
        public static Ability Imposter;
        public static Ability Infiltrator;
        public static Ability InnardsOut;
        public static Ability InnerFocus;
        public static Ability Insomnia;
        public static Ability Intimidate;
        public static Ability IronBarbs;
        public static Ability IronFist;
        public static Ability Justified;
        public static Ability KeenEye;
        public static Ability Klutz;
        public static Ability LeafGuard;
        public static Ability Levitate;
        public static Ability LightMetal;
        public static Ability LightningRod;
        public static Ability Limber;
        public static Ability LiquidOoze;
        public static Ability LiquidVoice;
        public static Ability LongReach;
        public static Ability MagicBounce;
        public static Ability MagicGuard;
        public static Ability Magician;
        public static Ability MagmaArmor;
        public static Ability MagnetPull;
        public static Ability MarvelScale;
        public static Ability MegaLauncher;
        public static Ability Merciless;
        public static Ability Minus;
        public static Ability MistySurge;
        public static Ability MoldBreaker;
        public static Ability Moody;
        public static Ability MotorDrive;
        public static Ability Moxie;
        public static Ability Multiscale;
        public static Ability Multitype;
        public static Ability Mummy;
        public static Ability NaturalCure;
        public static Ability NoGuard;
        public static Ability Normalize;
        public static Ability Oblivious;
        public static Ability Overcoat;
        public static Ability Overgrow;
        public static Ability OwnTempo;
        public static Ability ParentalBond;
        public static Ability Pickpocket;
        public static Ability Pickup;
        public static Ability Pixilate;
        public static Ability Plus;
        public static Ability PoisonHeal;
        public static Ability PoisonPoint;
        public static Ability PoisonTouch;
        public static Ability PowerConstruct;
        public static Ability PowerOfAlchemy;
        public static Ability Prankster;
        public static Ability Pressure;
        public static Ability PrimordialSea;
        public static Ability PrismArmor;
        public static Ability Protean;
        public static Ability PsychicSurge;
        public static Ability PurePower;
        public static Ability QueenlyMajesty;
        public static Ability QuickFeet;
        public static Ability RainDish;
        public static Ability Rattled;
        public static Ability Receiver;
        public static Ability Reckless;
        public static Ability Refrigerate;
        public static Ability Regenerator;
        public static Ability Rivalry;
        public static Ability RKSSystem;
        public static Ability RockHead;
        public static Ability RoughSkin;
        public static Ability RunAway;
        #endregion
        #region S-Z
        public static Ability SandForce;
        public static Ability SandRush;
        public static Ability SandStream;
        public static Ability SandVeil;
        public static Ability SapSipper;
        public static Ability Schooling;
        public static Ability Scrappy;
        public static Ability SereneGrace;
        public static Ability ShadowShield;
        public static Ability ShadowTag;
        public static Ability ShedSkin;
        public static Ability SheerForce;
        public static Ability ShellArmor;
        public static Ability ShieldDust;
        public static Ability ShieldsDown;
        public static Ability Simple;
        public static Ability SkillLink;
        public static Ability SlowStart;
        public static Ability SlushRush;
        public static Ability Sniper;
        public static Ability SnowCloak;
        public static Ability SnowWarning;
        public static Ability SolarPower;
        public static Ability SolidRock;
        public static Ability SoulHeart;
        public static Ability Soundproof;
        public static Ability SpeedBoost;
        public static Ability Stakeout;
        public static Ability Stall;
        public static Ability Stamina;
        public static Ability StanceChange;
        public static Ability Static;
        public static Ability Steadfast;
        public static Ability Steelworker;
        public static Ability Stench;
        public static Ability StickyHold;
        public static Ability StormDrain;
        public static Ability StrongJaw;
        public static Ability Sturdy;
        public static Ability SuctionCups;
        public static Ability SuperLuck;
        public static Ability SurgeSurfer;
        public static Ability Swarm;
        public static Ability SweetVeil;
        public static Ability SwiftSwim;
        public static Ability Symbiosis;
        public static Ability Synchronize;
        public static Ability TangledFeet;
        public static Ability TanglingHair;
        public static Ability Technician;
        public static Ability Telepathy;
        public static Ability Teravolt;
        public static Ability ThickFat;
        public static Ability TintedLens;
        public static Ability Torrent;
        public static Ability ToughClaws;
        public static Ability ToxicBoost;
        public static Ability Trace;
        public static Ability Triage;
        public static Ability Truant;
        public static Ability Turboblaze;
        public static Ability Unaware;
        public static Ability Unburden;
        public static Ability Unnerve;
        public static Ability VictoryStar;
        public static Ability VitalSpirit;
        public static Ability VoltAbsorb;
        public static Ability WaterAbsorb;
        public static Ability WaterBubble;
        public static Ability WaterCompaction;
        public static Ability WaterVeil;
        public static Ability WeakArmor;
        public static Ability WhiteSmoke;
        public static Ability WimpOut;
        public static Ability WonderGuard;
        public static Ability WonderSkin;
        public static Ability ZenMode;
        #endregion
        #endregion

        #region Definitions
        static Abilities()
        {
            #region A-H
            Adaptabililty = new Ability("Adaptability", "Powers up moves of the same type as the Pokémon.", 91);
            Aerilate = new Ability("Aerilate", "Contact with the Pokémon lowers the attacker's Speed stat.", 184);
            Aftermath = new Ability("Aftermath", "Damages the attacker if it contacts the Pokémon with a finishing hit.", 106);
            AirLock = new Ability("Air Lock", "Eliminates the effects of weather.", 76);
            Analytic = new Ability("Analytic", "Boosts move power when the Pokémon moves last.", 148);
            AngerPoint = new Ability("Anger Point", "The Pokémon is angered when it takes a critical hit, and that maxes its Attack stat.", 83);
            Anticipation = new Ability("Anticipation", "The Pokémon can sense an opposing Pokémon's dangerous moves.", 107);
            ArenaTrap = new Ability("Arena Trap", "Prevents opposing Pokémon from fleeing.", 71);
            AromaVeil = new Ability("Aroma Veil", "Protects itself and its allies from attacks that limit their move choices.", 165);
            AuraBreak = new Ability("Aura Break", "The effects of \"Aura\" Abilities are reversed to lower the power of affected moves.", 188);
            BadDreams = new Ability("Bad Dreams", "Reduces the HP of sleeping opposing Pokémon.", 123);
            Battery = new Ability("Battery", "Powers up ally Pokémon's special moves.", 217);
            BattleArmor = new Ability("Battle Armor", "Hard armor protects the Pokémon from critical hits.", 4);
            BattleBond = new Ability("Battle Bond", "Defeating an opposing Pokémon strengthens the Pokémon's bond with its Trainer, and it becomes Ash-Greninja. Water Shuriken gets more powerful.", 210);
            BeastBoost = new Ability("Beast Boost", "The Pokémon boosts its most proficient stat each time it knocks out a Pokémon.", 224);
            Beserk = new Ability("Beserk", "Boosts the Pokémon's Sp. Atk stat when it takes a hit that causes its HP to become half or less.", 201);
            BigPecks = new Ability("Big Pecks", "Protects the Pokémon from Defense-lowering effects.", 145);
            Blaze = new Ability("Blaze", "Powers up Fire-type moves when the Pokémon's HP is low.", 66);
            Bulletproof = new Ability("Bulletproof", "Protects the Pokémon from some ball and bomb moves.", 171);
            CheekPouch = new Ability("Cheek Pouch", "Restores HP as well when the Pokémon eats a Berry.", 167);
            Chlorophyll = new Ability("Chlorophyll", "Boosts the Pokémon's Speed stat in sunshine.", 34);
            ClearBody = new Ability("Clear Body", "Prevents other Pokémon's moves or Abilities from lowering the Pokémon's stats.", 29);
            CloudNine = new Ability("Cloud Nine", "Eliminates the effects of weather.", 13);
            ColorChange = new Ability("Color Change", "The Pokémon's type becomes the type of the move used on it.", 16);
            Comatose = new Ability("Comatose", "It's always drowsing and will never wake up. It can attack without waking up.", 213);
            Competitive = new Ability("Competitive", "Boosts the Sp. Atk stat sharply when a stat is lowered.", 172);
            CompoundEyes = new Ability("Compound Eyes", "The Pokémon's compound eyes boost its accuracy.", 14);
            Contrary = new Ability("Contrary", "Makes stat changes have an opposite effect.", 126);
            Corrosion = new Ability("Corrosion", "The Pokémon can poison the target even if it's a Steel or Poison type.", 212);
            CursedBody = new Ability("Cursed Body", "May disable a move used on the Pokémon.", 130);
            CuteCharm = new Ability("Cute Charm", "Contact with the Pokémon may cause infatuation.", 56);
            Damp = new Ability("Damp", "Prevents the use of explosive moves such as Self-Destruct by dampening its surroundings.", 6);
            Dancer = new Ability("Dancer", "When another Pokémon uses a dance move, it can use a dance move following it regardless of its Speed.", 216);
            DarkAura = new Ability("Dark Aura", "Powers up each Pokémon's Dark-type moves.", 186);
            Dazzling = new Ability("Dazzling", "Surprises the opposing Pokémon, making it unable to attack using priority moves.", 219);
            Defeatist = new Ability("Defeatist", "Halves the Pokémon's Attack and Sp. Atk stats when its HP becomes half or less.", 129);
            Defiant = new Ability("Defiant", "Boosts the Pokémon's Attack stat sharply when its stats are lowered.", 128);
            DeltaStream = new Ability("Delta Stream", "The Pokémon changes the weather to eliminate all of the Flying type's weaknesses.", 191);
            DesolateLand = new Ability("Desolate Land", "The Pokémon changes the weather to nullify Water-type attacks.", 190);
            Disguise = new Ability("Disguise", "Once per battle, the shroud that covers the Pokémon can protect it from an attack.", 209);
            Download = new Ability("Download", "Compares an opposing Pokémon's Defense and Sp. Def stats before raising its own Attack or Sp. Atk stat—whichever will be more effective.", 88);
            Drizzle = new Ability("Drizzle", "The Pokémon makes it rain when it enters a battle.", 2);
            Drought = new Ability("Drought", "Turns the sunlight harsh when the Pokémon enters a battle.", 70);
            DrySkin = new Ability("Dry Skin", "Restores HP in rain or when hit by Water-type moves. Reduces HP in sunshine, and increases the damage received from Fire-type moves.", 87);
            EarlyBird = new Ability("Early Bird", "The Pokémon awakens twice as fast as other Pokémon from sleep.", 48);
            EffectSpore = new Ability("Effect Spore", "Contact with the Pokémon may inflict poison, sleep, or paralysis on its attacker.", 27);
            ElectricSurge = new Ability("Electric Surge", "Turns the ground into Electric Terrain when the Pokémon enters a battle.", 226);
            EmergencyExit = new Ability("Emergency Exit", "The Pokémon, sensing danger, switches out when its HP becomes half or less.", 194);
            FairyAura = new Ability("Fairy Aura", "Powers up each Pokémon's Fairy-type moves.", 187);
            Filter = new Ability("Filter", "Reduces the power of supereffective attacks taken.", 111);
            FlameBody = new Ability("Flame Body", "Contact with the Pokémon may burn the attacker.", 49);
            FlareBoost = new Ability("Flare Boost", "Powers up special attacks when the Pokémon is burned.", 138);
            FlashFire = new Ability("Flash Fire", "Powers up the Pokémon's Fire-type moves if it's hit by one.", 18);
            FlowerGift = new Ability("Flower Gift", "Boosts the Attack and Sp. Def stats of itself and allies when it is sunny.", 122);
            FlowerVeil = new Ability("Flower Veil", "Ally Grass-type Pokémon are protected from status conditions and the lowering of their stats.", 166);
            Fluffy = new Ability("Fluffy", "Halves the damage taken from moves that make direct contact, but doubles that of Fire-type moves.", 218);
            Forecast = new Ability("Forecast", "The Pokémon transforms with the weather to change its type to Water, Fire, or Ice.", 59);
            Forewarn = new Ability("Forewarn", "When it enters a battle, the Pokémon can tell one of the moves an opposing Pokémon has.", 108);
            FriendGuard = new Ability("Friend Guard", "Reduces damage done to allies.", 132);
            Frisk = new Ability("Frisk", "When it enters a battle, the Pokémon can check an opposing Pokémon's held item.", 119);
            FullMetalBody = new Ability("Full Metal Body", "Prevents other Pokémon's moves or Abilities from lowering the Pokémon's stats.", 230);
            FurCoat = new Ability("Fur Coat", "Halves the damage from physical moves.", 169);
            GaleWings = new Ability("Gale Wings", "Gives priority to Flying-type moves when the Pokémon's HP is full.", 177);
            Galvanize = new Ability("Galvanize", "	Normal-type moves become Electric-type moves. The power of those moves is boosted a little.", 206);
            Gluttony = new Ability("Gluttony", "Makes the Pokémon eat a held Berry when its HP drops to half or less, which is sooner than usual.", 82);
            Gooey = new Ability("Gooey", "Contact with the Pokémon lowers the attacker's Speed stat.", 183);
            GrassPelt = new Ability("Grass Pelt", "Boosts the Pokémon's Defense stat in Grassy Terrain.", 179);
            GrassySurge = new Ability("Grassy Surge", "Turns the ground into Grassy Terrain when the Pokémon enters a battle.", 229);
            Guts = new Ability("Guts", "It's so gutsy that having a status condition boosts the Pokémon's Attack stat.", 62);
            Harvest = new Ability("Harvest", "May create another Berry after one is used.", 139);
            Healer = new Ability("Healer", "Sometimes heals an ally's status condition.", 131);
            Heatproof = new Ability("Heatproof", "The heatproof body of the Pokémon halves the damage from Fire-type moves that hit it.", 85);
            HeavyMetal = new Ability("Heavy Metal", "Doubles the Pokémon's weight.", 134);
            HoneyGather = new Ability("Honey Gather", "The Pokémon may gather Honey after a battle.", 118);
            HugePower = new Ability("Huge Power", "Doubles the Pokémon's Attack stat.", 37);
            Hustle = new Ability("Hustle", "Boosts the Attack stat, but lowers accuracy.", 55);
            Hydration = new Ability("Hydration", "Heals status conditions if it's raining.", 93);
            HyperCutter = new Ability("Hyper Cutter", "The Pokémon's proud of its powerful pincers. They prevent other Pokémon from lowering its Attack stat.", 52);
            #endregion
            #region I-R
            IceBody = new Ability("Ice Body", "The Pokémon gradually regains HP in a hailstorm.", 115);
            Illuminate = new Ability("Illuminate", "Raises the likelihood of meeting wild Pokémon by illuminating the surroundings.", 35);
            Illusion = new Ability("Illusion", "Comes out disguised as the Pokémon in the party's last spot.", 149);
            Immunity = new Ability("Immunity", "The immune system of the Pokémon prevents it from getting poisoned.", 17);
            Imposter = new Ability("Imposter", "The Pokémon transforms itself into the Pokémon it's facing.", 150);
            Infiltrator = new Ability("Infiltrator", "Passes through the opposing Pokémon's barrier, substitute, and the like and strikes.", 151);
            InnardsOut = new Ability("Innards Out", "Damages the attacker landing the finishing hit by the amount equal to its last HP.", 215);
            InnerFocus = new Ability("Inner Focus", "The Pokémon's intensely focused, and that protects the Pokémon from flinching.", 39);
            Insomnia = new Ability("Insomnia", "The Pokémon is suffering from insomnia and cannot fall asleep.", 15);
            Intimidate = new Ability("Intimidate", "The Pokémon intimidates opposing Pokémon upon entering battle, lowering their Attack stat.", 22);
            IronBarbs = new Ability("Iron Barbs", "Inflicts damage to the attacker on contact with iron barbs.", 160);
            IronFist = new Ability("Iron Fist", "Powers up punching moves.", 89);
            Justified = new Ability("Justified", "Being hit by a Dark-type move boosts the Attack stat of the Pokémon, for justice.", 154);
            KeenEye = new Ability("Keen Eye", "Keen eyes prevent other Pokémon from lowering this Pokémon's accuracy.", 51);
            Klutz = new Ability("Klutz", "The Pokémon can't use any held items.", 103);
            LeafGuard = new Ability("Leaf Guard", "Prevents status conditions in sunny weather.", 102);
            Levitate = new Ability("Levitate", "By floating in the air, the Pokémon receives full immunity to all Ground-type moves.", 26);
            LightMetal = new Ability("Light Metal", "Halves the Pokémon's weight.", 135);
            LightningRod = new Ability("Lightning Rod", "The Pokémon draws in all Electric-type moves. Instead of being hit by Electric-type moves, it boosts its Sp. Atk.", 31);
            Limber = new Ability("Limber", "Its limber body protects the Pokémon from paralysis.", 7);
            LiquidOoze = new Ability("Liquid Ooze", "Oozed liquid has strong stench, which damages attackers using any draining move.", 64);
            LiquidVoice = new Ability("Liquid Voice", "All sound-based moves become Water-type moves.", 204);
            LongReach = new Ability("Long Reach", "The Pokémon uses its moves without making contact with the target.", 203);
            MagicBounce = new Ability("Magic Bounce", "Reflects status moves, instead of getting hit by them.", 156);
            MagicGuard = new Ability("Magic Guard", "The Pokémon only takes damage from attacks.", 98);
            Magician = new Ability("Magician", "The Pokémon steals the held item of a Pokémon it hits with a move.", 170);
            MagmaArmor = new Ability("Magma Armor", "The Pokémon is covered with hot magma, which prevents the Pokémon from becoming frozen.", 40);
            MagnetPull = new Ability("Magnet Pull", "Prevents Steel-type Pokémon from escaping using its magnetic force.", 42);
            MarvelScale = new Ability("Marvel Scale", "The Pokémon's marvelous scales boost the Defense stat if it has a status condition.", 63);
            MegaLauncher = new Ability("Mega Launcher", "Powers up aura and pulse moves.", 178);
            Merciless = new Ability("Merciless", "The Pokémon's attacks become critical hits if the target is poisoned.", 196);
            Minus = new Ability("Minus", "Boosts the Sp. Atk stat of the Pokémon if an ally with the Plus or Minus Ability is also in battle.", 58);
            MistySurge = new Ability("Misty Surge", "Turns the ground into Misty Terrain when the Pokémon enters a battle.", 228);
            MoldBreaker = new Ability("Mold Breaker", "Moves can be used on the target regardless of its Abilities.", 104);
            Moody = new Ability("Moody", "Raises one stat sharply and lowers another every turn.", 141);
            MotorDrive = new Ability("Motor Drive", "Boosts its Speed stat if hit by an Electric-type move, instead of taking damage.", 78);
            Moxie = new Ability("Moxie", "The Pokémon shows moxie, and that boosts the Attack stat after knocking out any Pokémon.", 153);
            Multiscale = new Ability("Multiscale", "Reduces the amount of damage the Pokémon takes when its HP is full.", 136);
            Multitype = new Ability("Multitype", "Changes the Pokémon's type to match the Plate or Z-Crystal it holds.", 121);
            Mummy = new Ability("Mummy", "Contact with the Pokémon changes the attacker's Ability to Mummy.", 152);
            NaturalCure = new Ability("Natural Cure", "All status conditions heal when the Pokémon switches out.", 30);
            NoGuard = new Ability("No Guard", "The Pokémon employs no-guard tactics to ensure incoming and outgoing attacks always land.", 99);
            Normalize = new Ability("Normalize", "All the Pokémon's moves become Normal type. The power of those moves is boosted a little.", 96);
            Oblivious = new Ability("Oblivious", "The Pokémon is oblivious, and that keeps it from being infatuated or falling for taunts.", 12);
            Overcoat = new Ability("Overcoat", "Protects the Pokémon from things like sand, hail, and powder.", 142);
            Overgrow = new Ability("Overgrow", "Powers up Grass-type moves when the Pokémon's HP is low.", 65);
            OwnTempo = new Ability("Own Tempo", "This Pokémon has its own tempo, and that prevents it from becoming confused", 20);
            ParentalBond = new Ability("Parental Bond", "Parent and child each attacks.", 185);
            Pickpocket = new Ability("Pickpocket", "Steals an item from an attacker that made direct contact.", 124);
            Pickup = new Ability("Pickup", "The Pokémon may pick up the item an opposing Pokémon used during a battle. It may pick up items outside of battle, too.", 53);
            Pixilate = new Ability("Pixilate", "Normal-type moves become Fairy-type moves. The power of those moves is boosted a little.", 182);
            Plus = new Ability("Plus", "Boosts the Sp. Atk stat of the Pokémon if an ally with the Plus or Minus Ability is also in battle.", 57);
            PoisonHeal = new Ability("Poison Heal", "Restores HP if the Pokémon is poisoned, instead of losing HP.", 90);
            PoisonPoint = new Ability("Poison Point", "Contact with the Pokémon may poison the attacker.", 38);
            PoisonTouch = new Ability("Poison Touch", "May poison a target when the Pokémon makes contact.", 143);
            PowerConstruct = new Ability("Power Construct", "Other Cells gather to aid when its HP becomes half or less. Then the Pokémon changes its form to Complete Forme.", 211);
            PowerOfAlchemy = new Ability("Power of Alchemy", "The Pokémon copies the Ability of a defeated ally.", 223);
            Prankster = new Ability("Prankster", "Gives priority to a status move.", 158);
            Pressure = new Ability("Pressure", "By putting pressure on the opposing Pokémon, it raises their PP usage.", 46);
            PrimordialSea = new Ability("Primordial Sea", "The Pokémon changes the weather to nullify Fire-type attacks.", 189);
            PrismArmor = new Ability("Prism Armor", "Reduces the power of supereffective attacks taken.", 232);
            Protean = new Ability("Protean", "Changes the Pokémon's type to the type of the move it's about to use.", 168);
            PsychicSurge = new Ability("Psychic Surge", "Turns the ground into Psychic Terrain when the Pokémon enters a battle.", 227);
            PurePower = new Ability("Pure Power", "Using its pure power, the Pokémon doubles its Attack stat.", 74);
            QueenlyMajesty = new Ability("Queenly Majesty", "Its majesty pressures the opposing Pokémon, making it unable to attack using priority moves.", 214);
            QuickFeet = new Ability("Quick Feet", "Boosts the Speed stat if the Pokémon has a status condition.", 95);
            RainDish = new Ability("Rain Dish", "The Pokémon gradually regains HP in rain.", 44);
            Rattled = new Ability("Rattled", "Dark-, Ghost-, and Bug-type moves scare the Pokémon and boost its Speed stat.", 155);
            Receiver = new Ability("Receiver", "The Pokémon copies the Ability of a defeated ally.", 222);
            Reckless = new Ability("Reckless", "Powers up moves that have recoil damage.", 120);
            Refrigerate = new Ability("Refrigerate", "Normal-type moves become Ice-type moves. The power of those moves is boosted a little.", 174);
            Regenerator = new Ability("Regenerator", "Restores a little HP when withdrawn from battle.", 144);
            Rivalry = new Ability("Rivalry", "Becomes competitive and deals more damage to Pokémon of the same gender, but deals less to Pokémon of the opposite gender.", 79);
            RKSSystem = new Ability("RKS System", "Changes the Pokémon's type to match the memory disc it holds.", 225);
            RockHead = new Ability("Rock Head", "Protects the Pokémon from recoil damage.", 69);
            RoughSkin = new Ability("Rough Skin", "This Pokémon inflicts damage with its rough skin to the attacker on contact.", 24);
            RunAway = new Ability("Run Away", "Enables a sure getaway from wild Pokémon.", 50);
            #endregion
            #region S-Z
            SandForce = new Ability("Sand Force", "Boosts the power of Rock-, Ground-, and Steel-type moves in a sandstorm.", 159);
            SandRush = new Ability("Sand Rush", "Boosts the Pokémon's Speed stat in a sandstorm.", 146);
            SandStream = new Ability("Sand Stream", "The Pokémon summons a sandstorm when it enters a battle.", 45);
            SandVeil = new Ability("Sand Veil", "Boosts the Pokémon's evasion in a sandstorm.", 8);
            SapSipper = new Ability("Sap Sipper", "Boosts the Attack stat if hit by a Grass-type move, instead of taking damage.", 157);
            Schooling = new Ability("Schooling", "When it has a lot of HP, the Pokémon forms a powerful school. It stops schooling when its HP is low.", 208);
            Scrappy = new Ability("Scrappy", "The Pokémon can hit Ghost-type Pokémon with Normal- and Fighting-type moves.", 113);
            SereneGrace = new Ability("Serene Grace", "Boosts the likelihood of additional effects occurring when attacking.", 32);
            ShadowShield = new Ability("Shadow Shield", "Reduces the amount of damage the Pokémon takes while its HP is full.", 231);
            ShadowTag = new Ability("Shadow Tag", "This Pokémon steps on the opposing Pokémon's shadow to prevent it from escaping.", 23);
            ShedSkin = new Ability("Shed Skin", "The Pokémon may heal its own status conditions by shedding its skin.", 61);
            SheerForce = new Ability("Sheer Force", "Removes additional effects to increase the power of moves when attacking.", 125);
            ShellArmor = new Ability("Shell Armor", "A hard shell protects the Pokémon from critical hits.", 75);
            ShieldDust = new Ability("Shield Dust", "This Pokémon's dust blocks the additional effects of attacks taken.", 19);
            ShieldsDown = new Ability("Shields Down", "When its HP becomes half or less, the Pokémon's shell breaks and it becomes aggressive.", 197);
            Simple = new Ability("Simple", "The stat changes the Pokémon receives are doubled.", 86);
            SkillLink = new Ability("Skill Link", "Maximizes the number of times multi-strike moves hit.", 92);
            SlowStart = new Ability("Slow Start", "For five turns, the Pokémon's Attack and Speed stats are halved.", 112);
            SlushRush = new Ability("Slush Rush", "Boosts the Pokémon's Speed stat in a hailstorm.", 202);
            Sniper = new Ability("Sniper", "Powers up moves if they become critical hits when attacking.", 97);
            SnowCloak = new Ability("Snow Cloak", "Boosts evasion in a hailstorm.", 81);
            SnowWarning = new Ability("Snow Warning", "The Pokémon summons a hailstorm when it enters a battle.", 117);
            SolarPower = new Ability("Solar Power", "Boosts the Sp. Atk stat in sunny weather, but HP decreases every turn.", 94);
            SolidRock = new Ability("Solid Rock", "Reduces the power of supereffective attacks taken.", 116);
            SoulHeart = new Ability("Soul-Heart", "Boosts its Sp. Atk stat every time a Pokémon faints.", 220);
            Soundproof = new Ability("Soundproof", "Soundproofing of the Pokémon itself gives full immunity to all sound-based moves.", 43);
            SpeedBoost = new Ability("Speed Boost", "Its Speed stat is boosted every turn.", 3);
            Stakeout = new Ability("Stakeout", "Doubles the damage dealt to the target's replacement if the target switches out.", 198);
            Stall = new Ability("Stall", "The Pokémon moves after all other Pokémon do.", 100);
            Stamina = new Ability("Stamina", "Boosts the Defense stat when hit by an attack.", 192);
            StanceChange = new Ability("Stance Change", "The Pokémon changes its form to Blade Forme when it uses an attack move, and changes to Shield Forme when it uses King's Shield.", 176);
            Static = new Ability("Static", "The Pokémon is charged with static electricity, so contact with it may cause paralysis.", 9);
            Steadfast = new Ability("Steadfast", "The Pokémon's determination boosts the Speed stat each time the Pokémon flinches.", 80);
            Steelworker = new Ability("Steelworker", "Powers up Steel-type moves.", 200);
            Stench = new Ability("Stench", "By releasing stench when attacking, this Pokémon may cause the target to flinch.", 1);
            StickyHold = new Ability("Sticky Hold", "Items held by the Pokémon are stuck fast and cannot be removed by other Pokémon.", 60);
            StormDrain = new Ability("Storm Drain", "Draws in all Water-type moves. Instead of being hit by Water-type moves, it boosts its Sp. Atk.", 114);
            StrongJaw = new Ability("Strong Jaw", "The Pokémon's strong jaw boosts the power of its biting moves.", 173);
            Sturdy = new Ability("Sturdy", "It cannot be knocked out with one hit. One-hit KO moves cannot knock it out, either.", 5);
            SuctionCups = new Ability("Suction Cups", "This Pokémon uses suction cups to stay in one spot to negate all moves and items that force switching out.", 21);
            SuperLuck = new Ability("Super Luck", "The Pokémon is so lucky that the critical-hit ratios of its moves are boosted.", 105);
            SurgeSurfer = new Ability("Surge Surfer", "Doubles the Pokémon's Speed stat on Electric Terrain.", 207);
            Swarm = new Ability("Swarm", "Powers up Bug-type moves when the Pokémon's HP is low.", 68);
            SweetVeil = new Ability("Sweet Veil", "Prevents itself and ally Pokémon from falling asleep.", 175);
            SwiftSwim = new Ability("Swift Swim", "Boosts the Pokémon's Speed stat in rain.", 33);
            Symbiosis = new Ability("Symbiosis", "The Pokémon passes its item to an ally that has used up an item.", 180);
            Synchronize = new Ability("Synchronize", "The attacker will receive the same status condition if it inflicts a burn, poison, or paralysis to the Pokémon.", 28);
            TangledFeet = new Ability("Tangled Feet", "Raises evasion if the Pokémon is confused.", 77);
            TanglingHair = new Ability("Tangling Hair", "Contact with the Pokémon lowers the attacker's Speed stat.", 221);
            Technician = new Ability("Technician", "Powers up the Pokémon's weaker moves.", 101);
            Telepathy = new Ability("Telepathy", "Anticipates an ally's attack and dodges it.", 140);
            Teravolt = new Ability("Teravolt", "Moves can be used on the target regardless of its Abilities.", 164);
            ThickFat = new Ability("Thick Fat", "The Pokémon is protected by a layer of thick fat, which halves the damage taken from Fire- and Ice-type moves.", 47);
            TintedLens = new Ability("Tinted Lens", "The Pokémon can use \"not very effective\" moves to deal regular damage.", 110);
            Torrent = new Ability("Torrent", "Powers up Water-type moves when the Pokémon's HP is low.", 67);
            ToughClaws = new Ability("Tough Claws", "Powers up moves that make direct contact.", 181);
            ToxicBoost = new Ability("Toxic Boost", "Powers up physical attacks when the Pokémon is poisoned.", 137);
            Trace = new Ability("Trace", "When it enters a battle, the Pokémon copies an opposing Pokémon's Ability.", 36);
            Triage = new Ability("Triage", "Gives priority to a healing move.", 205);
            Truant = new Ability("Truant", "The Pokémon can't use a move the following turn if it uses one.", 54);
            Turboblaze = new Ability("Turboblaze", "Moves can be used on the target regardless of its Abilities.", 163);
            Unaware = new Ability("Unaware", "When attacking, the Pokémon ignores the target Pokémon's stat changes.", 109);
            Unburden = new Ability("Unburden", "Boosts the Speed stat if the Pokémon's held item is used or lost.", 84);
            Unnerve = new Ability("Unnerve", "Unnerves opposing Pokémon and makes them unable to eat Berries.", 127);
            VictoryStar = new Ability("Victory Star", "Boosts the accuracy of its allies and itself.", 162);
            VitalSpirit = new Ability("Vital Spirit", "The Pokémon is full of vitality, and that prevents it from falling asleep.", 72);
            VoltAbsorb = new Ability("Volt Absorb", "Restores HP if hit by an Electric-type move, instead of taking damage.", 10);
            WaterAbsorb = new Ability("Water Absorb", "Restores HP if hit by a Water-type move, instead of taking damage.", 11);
            WaterBubble = new Ability("Water Bubble", "Lowers the power of Fire-type moves done to the Pokémon and prevents the Pokémon from getting a burn.", 199);
            WaterCompaction = new Ability("Water Compaction", "Boosts the Pokémon's Defense stat sharply when hit by a Water-type move.", 195);
            WaterVeil = new Ability("Water Veil", "The Pokémon is covered with a water veil, which prevents the Pokémon from getting a burn.", 41);
            WeakArmor = new Ability("Weak Armor", "Physical attacks to the Pokémon lower its Defense stat but sharply raise its Speed stat.", 133);
            WhiteSmoke = new Ability("White Smoke", "The Pokémon is protected by its white smoke, which prevents other Pokémon from lowering its stats.", 73);
            WimpOut = new Ability("Wimp Out", "The Pokémon cowardly switches out when its HP becomes half or less.", 193);
            WonderGuard = new Ability("Wonder Guard", "Its mysterious power only lets supereffective moves hit the Pokémon.", 25);
            WonderSkin = new Ability("Wonder Skin", "Makes status moves more likely to miss.", 147);
            ZenMode = new Ability("Zen Mode", "Changes the Pokémon's shape when HP is half or less.", 161);
            #endregion
        }
        #endregion
    }
    #endregion
}
