using System.Collections.Generic;

namespace PokemonBattleSim
{
    public class Pokemon
    {
        #region Members
        /// <summary>
        /// The number of the Pokemon in the Pokedex
        /// </summary>
        int dexNum;
        /// <summary>
        /// The name of the Pokemon
        /// </summary>
        string name;
        /// <summary>
        /// Pokedex description of the Pokemon
        /// </summary>
        string desc;
        /// <summary>
        /// Primary type of the Pokemon
        /// </summary>
        BasicType type1;
        /// <summary>
        /// Secondary type of the Pokemon
        /// </summary>
        BasicType type2;
        /// <summary>
        /// List of possible abilities, the final one being the HA
        /// </summary>
        List<Ability> possAbilities;
        /// <summary>
        /// Enumerates the base stats of the pkmn
        /// </summary>
        List<PkmnStat> baseStats;
        /// <summary>
        /// List of possible moves
        /// </summary>
        List<Move> possMoves;
        /// <summary>
        /// Used to create the list of base stats from the int array
        /// </summary>
        static Stat[] statOrder = new Stat[8] { Stats.HP, Stats.Atk, Stats.Def, Stats.SpAtk, Stats.SpDef, Stats.Spd, Stats.Happiness, Stats.Weight };
        #endregion

        #region Constructor
        public Pokemon(int dexnum, string n, string d, BasicType typeA, BasicType typeB, Ability[] abilities, double[] stats, Move[] moves)
        {
            dexNum = dexnum;
            name = n;
            desc = d;
            type1 = typeA;
            type2 = typeB;
            possAbilities = new List<Ability>(abilities);
            possMoves = new List<Move>(moves);

            PkmnStat[] pkmnstats = new PkmnStat[10];
            for (int i = 0; i < 8; i++)
            {
                pkmnstats[i] = new PkmnStat(stats[i], statOrder[i]);
            }
            pkmnstats[8] = new PkmnStat(1, Stats.Accuracy);
            pkmnstats[9] = new PkmnStat(1, Stats.Evasion);
            baseStats = new List<PkmnStat>(pkmnstats);
        }
        #endregion
    }

    public static class Pkmn
    {
        #region Declarations

        #region Kanto
        public static Pokemon Bulbasaur;
        public static Pokemon Ivysaur;
        public static Pokemon Venusaur;
        public static Pokemon MegaVenusaur;
        public static Pokemon Charmander;
        public static Pokemon Charmeleon;
        public static Pokemon Charizard;
        public static Pokemon MegaCharizardX;
        public static Pokemon MegaCharizardY;
        public static Pokemon Squirtle;
        public static Pokemon Wartortle;
        public static Pokemon Blastoise;
        public static Pokemon MegaBlastoise;
        public static Pokemon Caterpie;
        public static Pokemon Metapod;
        public static Pokemon Butterfree;
        public static Pokemon Weedle;
        public static Pokemon Kakuna;
        public static Pokemon Beedrill;
        public static Pokemon MegaBeedrill;
        public static Pokemon Pidgey;
        public static Pokemon Pidgeotto;
        public static Pokemon Pidgeot;
        public static Pokemon MegaPidgeot;
        public static Pokemon Rattata;
        public static Pokemon AlolanRattata;
        public static Pokemon Raticate;
        public static Pokemon AlolanRaticate;
        public static Pokemon Spearow;
        public static Pokemon Fearow;
        public static Pokemon Ekans;
        public static Pokemon Arbok;
        public static Pokemon Pikachu;
        public static Pokemon Raichu;
        public static Pokemon AlolanRaichu;
        public static Pokemon Sandshrew;
        public static Pokemon AlolanSandshrew;
        public static Pokemon Sandslash;
        public static Pokemon AlolanSandslash;
        public static Pokemon NidoranGirl;
        public static Pokemon Nidorina;
        public static Pokemon Nidoqueen;
        public static Pokemon NidoranBoy;
        public static Pokemon Nidorino;
        public static Pokemon Nidoking;
        public static Pokemon Clefairy;
        public static Pokemon Clefable;
        public static Pokemon Vulpix;
        public static Pokemon AlolanVulpix;
        public static Pokemon Ninetales;
        public static Pokemon AlolanNinetales;
        public static Pokemon Jigglypuff;
        public static Pokemon Wigglytuff;
        public static Pokemon Zubat;
        public static Pokemon Golbat;
        public static Pokemon Oddish;
        public static Pokemon Gloom;
        public static Pokemon Vileplume;
        public static Pokemon Paras;
        public static Pokemon Parasect;
        public static Pokemon Venonat;
        public static Pokemon Venomoth;
        public static Pokemon Diglett;
        public static Pokemon AlolanDiglett;
        public static Pokemon Dugtrio;
        public static Pokemon AlolanDugtrio;
        public static Pokemon Meowth;
        public static Pokemon AlolanMeowth;
        public static Pokemon Persian;
        public static Pokemon AlolanPersian;
        public static Pokemon Psyduck;
        public static Pokemon Golduck;
        public static Pokemon Mankey;
        public static Pokemon Primeape;
        public static Pokemon Growlithe;
        public static Pokemon Arcanine;
        public static Pokemon Poliwag;
        public static Pokemon Poliwhirl;
        public static Pokemon Poliwrath;
        public static Pokemon Abra;
        public static Pokemon Kadabra;
        public static Pokemon Alakazam;
        public static Pokemon MegaAlakazam;
        public static Pokemon Machop;
        public static Pokemon Machoke;
        public static Pokemon Machamp;
        public static Pokemon Bellsprout;
        public static Pokemon Weepinbell;
        public static Pokemon Victreebel;
        public static Pokemon Tentacool;
        public static Pokemon Tentacruel;
        public static Pokemon Geodude;
        public static Pokemon AlolanGeodude;
        public static Pokemon Graveler;
        public static Pokemon AlolanGraveler;
        public static Pokemon Golem;
        public static Pokemon AlolanGolem;
        public static Pokemon Ponyta;
        public static Pokemon Rapidash;
        public static Pokemon Slowpoke;
        public static Pokemon Slowbro;
        public static Pokemon MegaSlowbro;
        public static Pokemon Magnemite;
        public static Pokemon Magneton;
        public static Pokemon Farfetchd;
        public static Pokemon Doduo;
        public static Pokemon Dodrio;
        public static Pokemon Seel;
        public static Pokemon Dewgong;
        public static Pokemon Grimer;
        public static Pokemon AlolanGrimer;
        public static Pokemon Muk;
        public static Pokemon AlolanMuk;
        public static Pokemon Shellder;
        public static Pokemon Cloyster;
        public static Pokemon Gastly;
        public static Pokemon Haunter;
        public static Pokemon Gengar;
        public static Pokemon MegaGengar;
        public static Pokemon Onix;
        public static Pokemon Drowzee;
        public static Pokemon Hypno;
        public static Pokemon Krabby;
        public static Pokemon Kingler;
        public static Pokemon Voltorb;
        public static Pokemon Electrode;
        public static Pokemon Exeggcute;
        public static Pokemon Exeggutor;
        public static Pokemon AlolanExeggutor;
        public static Pokemon Cubone;
        public static Pokemon Marowak;
        public static Pokemon AlolanMarowak;
        public static Pokemon Hitmonlee;
        public static Pokemon Hitmonchan;
        public static Pokemon Lickitung;
        public static Pokemon Koffing;
        public static Pokemon Weezing;
        public static Pokemon Rhyhorn;
        public static Pokemon Rhydon;
        public static Pokemon Chansey;
        public static Pokemon Tangela;
        public static Pokemon Kangaskhan;
        public static Pokemon AlolanKangaskhan;
        public static Pokemon Horsea;
        public static Pokemon Seadra;
        public static Pokemon Goldeen;
        public static Pokemon Seaking;
        public static Pokemon Staryu;
        public static Pokemon Starmie;
        public static Pokemon MrMime;
        public static Pokemon Scyther;
        public static Pokemon Jynx;
        public static Pokemon Electabuzz;
        public static Pokemon Magmar;
        public static Pokemon Pinsir;
        public static Pokemon MegaPinsir;
        public static Pokemon Tauros;
        public static Pokemon Magikarp;
        public static Pokemon Gyarados;
        public static Pokemon MegaGyarados;
        public static Pokemon Lapras;
        public static Pokemon Ditto;
        public static Pokemon Eevee;
        public static Pokemon Vaporeon;
        public static Pokemon Jolteon;
        public static Pokemon Flareon;
        public static Pokemon Porygon;
        public static Pokemon Omanyte;
        public static Pokemon Omaster;
        public static Pokemon Kabuto;
        public static Pokemon Kabutops;
        public static Pokemon Aerodactyl;
        public static Pokemon MegaAerodactyl;
        public static Pokemon Snorlax;
        public static Pokemon Articuno;
        public static Pokemon Zapdos;
        public static Pokemon Moltres;
        public static Pokemon Dratini;
        public static Pokemon Dragonair;
        public static Pokemon Dragonite;
        public static Pokemon Mewtwo;
        public static Pokemon MegaMewtwoX;
        public static Pokemon MegaMewtwoY;
        public static Pokemon Mew;
        #endregion

        #region Johto
        public static Pokemon Chikorita;
        public static Pokemon Bayleef;
        public static Pokemon Meganium;
        public static Pokemon Cyndaquil;
        public static Pokemon Quilava;
        public static Pokemon Typhlosion;
        public static Pokemon Totodile;
        public static Pokemon Croconaw;
        public static Pokemon Feraligatr;
        public static Pokemon Sentret;
        public static Pokemon Furret;
        public static Pokemon Hoothoot;
        public static Pokemon Noctowl;
        public static Pokemon Ledyba;
        public static Pokemon Ledian;
        public static Pokemon Spinarak;
        public static Pokemon Ariados;
        public static Pokemon Crobat;
        public static Pokemon Chinchou;
        public static Pokemon Lanturn;
        public static Pokemon Pichu;
        public static Pokemon Cleffa;
        public static Pokemon Igglybuff;
        public static Pokemon Togepi;
        public static Pokemon Togetic;
        public static Pokemon Natu;
        public static Pokemon Xatu;
        public static Pokemon Mareep;
        public static Pokemon Flaaffy;
        public static Pokemon Ampharos;
        public static Pokemon MegaAmpharos;
        public static Pokemon Bellossom;
        public static Pokemon Marill;
        public static Pokemon Azumarill;
        public static Pokemon Sudowoodo;
        public static Pokemon Politoed;
        public static Pokemon Hoppip;
        public static Pokemon Skiploom;
        public static Pokemon Jumpluff;
        public static Pokemon Aipom;
        public static Pokemon Sunkern;
        public static Pokemon Sunflora;
        public static Pokemon Yanma;
        public static Pokemon Wooper;
        public static Pokemon Quagsire;
        public static Pokemon Espeon;
        public static Pokemon Umbreon;
        public static Pokemon Murkrow;
        public static Pokemon Slowking;
        public static Pokemon Misdreavus;
        public static Pokemon Unown;
        public static Pokemon Wobbuffet;
        public static Pokemon Girafarig;
        public static Pokemon Pineco;
        public static Pokemon Forretress;
        public static Pokemon Dunsparce;
        public static Pokemon Gligar;
        public static Pokemon Steelix;
        public static Pokemon MegaSteelix;
        public static Pokemon Snubbull;
        public static Pokemon Granbull;
        public static Pokemon Qwilfish;
        public static Pokemon Scizor;
        public static Pokemon MegaScizor;
        public static Pokemon Shuckle;
        public static Pokemon Heracross;
        public static Pokemon MegaHeracross;
        public static Pokemon Sneasel;
        public static Pokemon Teddiursa;
        public static Pokemon Ursaring;
        public static Pokemon Slugma;
        public static Pokemon Magcargo;
        public static Pokemon Swinub;
        public static Pokemon Piloswine;
        public static Pokemon Corsola;
        public static Pokemon Reomraid;
        public static Pokemon Octillery;
        public static Pokemon Delibird;
        public static Pokemon Mantine;
        public static Pokemon Skarmory;
        public static Pokemon Houndour;
        public static Pokemon Houndoom;
        public static Pokemon MegaHoundoom;
        public static Pokemon Kingdra;
        public static Pokemon Phanpy;
        public static Pokemon Donphan;
        public static Pokemon Porygon2;
        public static Pokemon Stantler;
        public static Pokemon Smeargle;
        public static Pokemon Tyrogue;
        public static Pokemon Hitmontop;
        public static Pokemon Smoochum;
        public static Pokemon Elekid;
        public static Pokemon Magby;
        public static Pokemon Miltank;
        public static Pokemon Blissey;
        public static Pokemon Raikou;
        public static Pokemon Entei;
        public static Pokemon Suicune;
        public static Pokemon Larvitar;
        public static Pokemon Pupitar;
        public static Pokemon Tyranitar;
        public static Pokemon MegaTyranitar;
        public static Pokemon Lugia;
        public static Pokemon HoOh;
        public static Pokemon Celebi;
        #endregion

        #region Hoenn
        public static Pokemon Treecko;
        public static Pokemon Grovyle;
        public static Pokemon Sceptile;
        public static Pokemon MegaSceptile;
        public static Pokemon Torchic;
        public static Pokemon Combusken;
        public static Pokemon Blaziken;
        public static Pokemon MegaBlaziken;
        public static Pokemon Mudkip;
        public static Pokemon Marshtomp;
        public static Pokemon Swampert;
        public static Pokemon MegaSwampert;
        public static Pokemon Poochyena;
        public static Pokemon Mightyena;
        public static Pokemon Zigzagoon;
        public static Pokemon Linoone;
        public static Pokemon Wurmple;
        public static Pokemon Silcoon;
        public static Pokemon Beautifly;
        public static Pokemon Cascoon;
        public static Pokemon Dustox;
        public static Pokemon Lotad;
        public static Pokemon Lombre;
        public static Pokemon Ludicolo;
        public static Pokemon Seedot;
        public static Pokemon Nuzleaf;
        public static Pokemon Shiftry;
        public static Pokemon Taillow;
        public static Pokemon Swellow;
        public static Pokemon Wingull;
        public static Pokemon Pelipper;
        public static Pokemon Ralts;
        public static Pokemon Kirlia;
        public static Pokemon Gardevoir;
        public static Pokemon MegaGardevoir;
        public static Pokemon Surskit;
        public static Pokemon Masquerain;
        public static Pokemon Shroomish;
        public static Pokemon Breloom;
        public static Pokemon Slakoth;
        public static Pokemon Vigoroth;
        public static Pokemon Slaking;
        public static Pokemon Nincada;
        public static Pokemon Ninjask;
        public static Pokemon Shedinja;
        public static Pokemon Whismur;
        public static Pokemon Loudred;
        public static Pokemon Exploud;
        public static Pokemon Makuhita;
        public static Pokemon Hariyama;
        public static Pokemon Azurill;
        public static Pokemon Nosepass;
        public static Pokemon Skitty;
        public static Pokemon Delcatty;
        public static Pokemon Sableye;
        public static Pokemon MegaSableye;
        public static Pokemon Mawile;
        public static Pokemon MegaMawile;
        public static Pokemon Aron;
        public static Pokemon Lairon;
        public static Pokemon Aggron;
        public static Pokemon MegaAggron;
        public static Pokemon Meditite;
        public static Pokemon Medicham;
        public static Pokemon MegaMedicham;
        public static Pokemon Electrike;
        public static Pokemon Manectric;
        public static Pokemon MegaManectric;
        public static Pokemon Plusle;
        public static Pokemon Minun;
        public static Pokemon Volbeat;
        public static Pokemon Illumise;
        public static Pokemon Roselia;
        public static Pokemon Gulpin;
        public static Pokemon Swalot;
        public static Pokemon Carvanha;
        public static Pokemon Sharpedo;
        public static Pokemon MegaSharpedo;
        public static Pokemon Wailmer;
        public static Pokemon Wailord;
        public static Pokemon Numel;
        public static Pokemon Camerupt;
        public static Pokemon MegaCamerupt;
        public static Pokemon Torkoal;
        public static Pokemon Spoink;
        public static Pokemon Grumpig;
        public static Pokemon Spinda;
        public static Pokemon Trapinch;
        public static Pokemon Vibrava;
        public static Pokemon Flygon;
        public static Pokemon Cacnea;
        public static Pokemon Cacturne;
        public static Pokemon Swablu;
        public static Pokemon Altaria;
        public static Pokemon MegaAltaria;
        public static Pokemon Zangoose;
        public static Pokemon Seviper;
        public static Pokemon Lunatone;
        public static Pokemon Solrock;
        public static Pokemon Barboach;
        public static Pokemon Whiscash;
        public static Pokemon Corphish;
        public static Pokemon Crawdaunt;
        public static Pokemon Baltoy;
        public static Pokemon Claydol;
        public static Pokemon Lileep;
        public static Pokemon Cradily;
        public static Pokemon Anorith;
        public static Pokemon Armaldo;
        public static Pokemon Feebas;
        public static Pokemon Milotic;
        public static Pokemon Castform;
        public static Pokemon Kecleon;
        public static Pokemon Shuppet;
        public static Pokemon Banette;
        public static Pokemon MegaBanette;
        public static Pokemon Duskull;
        public static Pokemon Dusclops;
        public static Pokemon Tropius;
        public static Pokemon Chimecho;
        public static Pokemon Absol;
        public static Pokemon MegaAbsol;
        public static Pokemon Wynaut;
        public static Pokemon Snorunt;
        public static Pokemon Glalie;
        public static Pokemon MegaGlalie;
        public static Pokemon Spheal;
        public static Pokemon Sealeo;
        public static Pokemon Walrein;
        public static Pokemon Clamperl;
        public static Pokemon Huntail;
        public static Pokemon Gorebyss;
        public static Pokemon Relicanth;
        public static Pokemon Luvdisc;
        public static Pokemon Bagon;
        public static Pokemon Shelgon;
        public static Pokemon Salamence;
        public static Pokemon MegaSalamence;
        public static Pokemon Beldum;
        public static Pokemon Metang;
        public static Pokemon Metagross;
        public static Pokemon MegaMetagross;
        public static Pokemon Regirock;
        public static Pokemon Regice;
        public static Pokemon Registeel;
        public static Pokemon Latias;
        public static Pokemon MegaLatias;
        public static Pokemon Latios;
        public static Pokemon MegaLatios;
        public static Pokemon Kyogre;
        public static Pokemon PrimalKyogre;
        public static Pokemon Groudon;
        public static Pokemon PrimalGroudon;
        public static Pokemon Rayquaza;
        public static Pokemon MegaRayquaza;
        public static Pokemon Jirachi;
        public static Pokemon NormalDeoxys;
        public static Pokemon AttackDeoxys;
        public static Pokemon DefenseDeoxys;
        public static Pokemon SpeedDeoxys;
        #endregion

        #region Sinnoh
        public static Pokemon Turtwig;
        public static Pokemon Grotle;
        public static Pokemon Torterra;
        public static Pokemon Chimchar;
        public static Pokemon Monferno;
        public static Pokemon Infernape;
        public static Pokemon Piplup;
        public static Pokemon Empoleon;
        public static Pokemon Starly;
        public static Pokemon Staravia;
        public static Pokemon Staraptor;
        public static Pokemon Bidoof;
        public static Pokemon Bibarel;
        public static Pokemon Kricketot;
        public static Pokemon Kricketune;
        public static Pokemon Shinx;
        public static Pokemon Luxio;
        public static Pokemon Luxray;
        public static Pokemon Budew;
        public static Pokemon Roserade;
        public static Pokemon Cranidos;
        public static Pokemon Rampardos;
        public static Pokemon Shieldon;
        public static Pokemon Bastiodon;
        public static Pokemon Burmy;
        public static Pokemon TrashWormadam;
        public static Pokemon SandyWormadam;
        public static Pokemon PlantWormadam;
        public static Pokemon Mothim;
        public static Pokemon Combee;
        public static Pokemon Vespiquen;
        public static Pokemon Pachirisu;
        public static Pokemon Buizel;
        public static Pokemon Floatzel;
        public static Pokemon Cherubi;
        public static Pokemon Cherrim;
        public static Pokemon Shellos;
        public static Pokemon Gastrodon;
        public static Pokemon Ambipom;
        public static Pokemon Drifloon;
        public static Pokemon Drifblim;
        public static Pokemon Buneary;
        public static Pokemon Lopunny;
        public static Pokemon MegaLopunny;
        public static Pokemon Mismagius;
        public static Pokemon Honchkrow;
        public static Pokemon Glameow;
        public static Pokemon Purugly;
        public static Pokemon Chingling;
        public static Pokemon Stunky;
        public static Pokemon Skuntank;
        public static Pokemon Bronzor;
        public static Pokemon Bronzong;
        public static Pokemon Bonsly;
        public static Pokemon MimeJr;
        public static Pokemon Happiny;
        public static Pokemon Chatot;
        public static Pokemon Spiritomb;
        public static Pokemon Gible;
        public static Pokemon Gabite;
        public static Pokemon Garchomp;
        public static Pokemon MegaGarchomp;
        public static Pokemon Munchlax;
        public static Pokemon Riolu;
        public static Pokemon Lucario;
        public static Pokemon MegaLucario;
        public static Pokemon Hippopotas;
        public static Pokemon Hippowdon;
        public static Pokemon Skorupi;
        public static Pokemon Drapion;
        public static Pokemon Croagunk;
        public static Pokemon Toxicroak;
        public static Pokemon Carnivine;
        public static Pokemon Finneon;
        public static Pokemon Lumineon;
        public static Pokemon Mantyke;
        public static Pokemon Snover;
        public static Pokemon Abomasnow;
        public static Pokemon MegaAbomasnow;
        public static Pokemon Weavile;
        public static Pokemon Magnezone;
        public static Pokemon Lickilicky;
        public static Pokemon Rhyperior;
        public static Pokemon Tangrowth;
        public static Pokemon Electivire;
        public static Pokemon Magmortar;
        public static Pokemon Togekiss;
        public static Pokemon Yanmega;
        public static Pokemon Leafeon;
        public static Pokemon Glaceon;
        public static Pokemon Gliscor;
        public static Pokemon Mamoswine;
        public static Pokemon PorygonZ;
        public static Pokemon Gallade;
        public static Pokemon MegaGallade;
        public static Pokemon Probopass;
        public static Pokemon Dusknoir;
        public static Pokemon Froslass;
        public static Pokemon Rotom;
        public static Pokemon FrostRotom;
        public static Pokemon FanRotom;
        public static Pokemon MowRotom;
        public static Pokemon WashRotom;
        public static Pokemon HeatRotom;
        public static Pokemon Uxie;
        public static Pokemon Mespirit;
        public static Pokemon Azelf;
        public static Pokemon Dialga;
        public static Pokemon Palkia;
        public static Pokemon Heatran;
        public static Pokemon Regigigas;
        public static Pokemon Giratina;
        public static Pokemon OriginGiratina;
        public static Pokemon Cresselia;
        public static Pokemon Phione;
        public static Pokemon Manaphy;
        public static Pokemon Darkrai;
        public static Pokemon Shaymin;
        public static Pokemon SkyShaymin;
        public static Pokemon Arceus;
        #endregion

        #region Unova
        public static Pokemon Victini;
        public static Pokemon Snivy;
        public static Pokemon Servine;
        public static Pokemon Serperior;
        public static Pokemon Tepig;
        public static Pokemon Pignite;
        public static Pokemon Emboar;
        public static Pokemon Oshawott;
        public static Pokemon Dewott;
        public static Pokemon Samurott;
        public static Pokemon Patrat;
        public static Pokemon Watchog;
        public static Pokemon Lillipup;
        public static Pokemon Herdier;
        public static Pokemon Stoutland;
        public static Pokemon Purrloin;
        public static Pokemon Liepard;
        public static Pokemon Pansage;
        public static Pokemon Simisage;
        public static Pokemon Pansear;
        public static Pokemon Simisear;
        public static Pokemon Panpour;
        public static Pokemon Simipour;
        public static Pokemon Munna;
        public static Pokemon Musharna;
        public static Pokemon Pidove;
        public static Pokemon Tranquill;
        public static Pokemon Unfezant;
        public static Pokemon Blitzle;
        public static Pokemon Zebstrika;
        public static Pokemon Roggenrola;
        public static Pokemon Boldore;
        public static Pokemon Gigalith;
        public static Pokemon Woobat;
        public static Pokemon Swoobat;
        public static Pokemon Drilbur;
        public static Pokemon Excadrill;
        public static Pokemon Audino;
        public static Pokemon MegaAudino;
        public static Pokemon Timburr;
        public static Pokemon Gurdurr;
        public static Pokemon Conkeldurr;
        public static Pokemon Tympole;
        public static Pokemon Palpitoad;
        public static Pokemon Seismitoad;
        public static Pokemon Throh;
        public static Pokemon Sawk;
        public static Pokemon Sewaddle;
        public static Pokemon Swadloon;
        public static Pokemon Leavanny;
        public static Pokemon Venipede;
        public static Pokemon Whirlipede;
        public static Pokemon Scolipede;
        public static Pokemon Cottonee;
        public static Pokemon Whimsicott;
        public static Pokemon Petilil;
        public static Pokemon Lilligant;
        public static Pokemon Basculin;
        public static Pokemon Sandile;
        public static Pokemon Krokorok;
        public static Pokemon Krookodile;
        public static Pokemon Darumaka;
        public static Pokemon Darmanitan;
        public static Pokemon ZenDarmanitan;
        public static Pokemon Maractus;
        public static Pokemon Dwebble;
        public static Pokemon Crustle;
        public static Pokemon Scraggy;
        public static Pokemon Scrafty;
        public static Pokemon Sigilyph;
        public static Pokemon Yamask;
        public static Pokemon Cofagrigus;
        public static Pokemon Tirtouga;
        public static Pokemon Carracosta;
        public static Pokemon Archen;
        public static Pokemon Archeops;
        public static Pokemon Trubbish;
        public static Pokemon Garbodor;
        public static Pokemon Zorua;
        public static Pokemon Zoroark;
        public static Pokemon Minccino;
        public static Pokemon Cinccino;
        public static Pokemon Gothita;
        public static Pokemon Gothorita;
        public static Pokemon Gothitelle;
        public static Pokemon Solosis;
        public static Pokemon Duosion;
        public static Pokemon Reuniclus;
        public static Pokemon Ducklett;
        public static Pokemon Swanna;
        public static Pokemon Vanillite;
        public static Pokemon Vanillish;
        public static Pokemon Vanilluxe;
        public static Pokemon Deerling;
        public static Pokemon Sawsbuck;
        public static Pokemon Emolga;
        public static Pokemon Karrablast;
        public static Pokemon Escavalier;
        public static Pokemon Foongus;
        public static Pokemon Amoonguss;
        public static Pokemon Frillish;
        public static Pokemon Jellicent;
        public static Pokemon Alomomola;
        public static Pokemon Joltik;
        public static Pokemon Galvantula;
        public static Pokemon Ferroseed;
        public static Pokemon Ferrothorn;
        public static Pokemon Kilnk;
        public static Pokemon Klang;
        public static Pokemon Klinklang;
        public static Pokemon Tynamo;
        public static Pokemon Eelektrik;
        public static Pokemon Eelektross;
        public static Pokemon Elgyem;
        public static Pokemon Beheeyem;
        public static Pokemon Litwick;
        public static Pokemon Lampent;
        public static Pokemon Chandelure;
        public static Pokemon Axew;
        public static Pokemon Fraxure;
        public static Pokemon Haxorus;
        public static Pokemon Cubchoo;
        public static Pokemon Beartic;
        public static Pokemon Cryogonal;
        public static Pokemon Shelmet;
        public static Pokemon Accelgor;
        public static Pokemon Stunfisk;
        public static Pokemon Mienfoo;
        public static Pokemon Mienshao;
        public static Pokemon Druddigon;
        public static Pokemon Golett;
        public static Pokemon Golurk;
        public static Pokemon Pawniard;
        public static Pokemon Bisharp;
        public static Pokemon Bouffalant;
        public static Pokemon Rufflet;
        public static Pokemon Braviary;
        public static Pokemon Vullaby;
        public static Pokemon Mandibuzz;
        public static Pokemon Heatmor;
        public static Pokemon Durant;
        public static Pokemon Deino;
        public static Pokemon Zweilous;
        public static Pokemon Hydreigon;
        public static Pokemon Larvesta;
        public static Pokemon Volcarona;
        public static Pokemon Cobalion;
        public static Pokemon Terrakion;
        public static Pokemon Virizion;
        public static Pokemon Tornadus;
        public static Pokemon TherianTornadus;
        public static Pokemon Thundurus;
        public static Pokemon TherianThundurus;
        public static Pokemon Reshiram;
        public static Pokemon Zekrom;
        public static Pokemon Landorus;
        public static Pokemon TherianLandorus;
        public static Pokemon Kyurem;
        public static Pokemon BlackKyurem;
        public static Pokemon WhiteKyurem;
        public static Pokemon Keldeo;
        public static Pokemon ResoluteKeldeo;
        public static Pokemon Meloetta;
        public static Pokemon PirouetteMeloetta;
        public static Pokemon Genesect;
        #endregion

        #region Kalos
        public static Pokemon Chespin;
        public static Pokemon Quilladin;
        public static Pokemon Chesnaught;
        public static Pokemon Fennekin;
        public static Pokemon Braixen;
        public static Pokemon Delphox;
        public static Pokemon Froakie;
        public static Pokemon Frogadier;
        public static Pokemon Greninja;
        public static Pokemon AshGreninja;
        public static Pokemon Bunnelby;
        public static Pokemon Diggersby;
        public static Pokemon Fletchling;
        public static Pokemon Fletchinder;
        public static Pokemon Talonflame;
        public static Pokemon Scatterbug;
        public static Pokemon Spewpa;
        public static Pokemon Vivillon;
        public static Pokemon Litleo;
        public static Pokemon Pyroar;
        public static Pokemon Flabebe;
        public static Pokemon Floette;
        public static Pokemon Florges;
        public static Pokemon Skiddo;
        public static Pokemon Gogoat;
        public static Pokemon Pancham;
        public static Pokemon Pangoro;
        public static Pokemon Furfrou;
        public static Pokemon Espurr;
        public static Pokemon MaleMeowstic;
        public static Pokemon FemaleMeowstic;
        public static Pokemon Honedge;
        public static Pokemon Doublade;
        public static Pokemon ShieldAegislash;
        public static Pokemon BladeAegislash;
        public static Pokemon Spritzee;
        public static Pokemon Aromatisse;
        public static Pokemon Swirlix;
        public static Pokemon Slurpuff;
        public static Pokemon Inkay;
        public static Pokemon Malamar;
        public static Pokemon Binacle;
        public static Pokemon Barbaracle;
        public static Pokemon Skrelp;
        public static Pokemon Dragalge;
        public static Pokemon Clauncher;
        public static Pokemon Clawitzer;
        public static Pokemon Helioptile;
        public static Pokemon Heliolisk;
        public static Pokemon Tyrunt;
        public static Pokemon Tyrantrum;
        public static Pokemon Amaura;
        public static Pokemon Aurorus;
        public static Pokemon Sylveon;
        public static Pokemon Hawlucha;
        public static Pokemon Dedenne;
        public static Pokemon Carbink;
        public static Pokemon Goomy;
        public static Pokemon Sliggoo;
        public static Pokemon Goodra;
        public static Pokemon Klefki;
        public static Pokemon Phantump;
        public static Pokemon Trevenant;
        public static Pokemon Pumpkaboo;
        public static Pokemon SmallPumpkaboo;
        public static Pokemon LargePumpkaboo;
        public static Pokemon SuperPumpkaboo;
        public static Pokemon Gourgeist;
        public static Pokemon SmallGourgeist;
        public static Pokemon LargeGourgeist;
        public static Pokemon SuperGourgeist;
        public static Pokemon Bergmite;
        public static Pokemon Avalugg;
        public static Pokemon Noibat;
        public static Pokemon Noivern;
        public static Pokemon Xerneas;
        public static Pokemon Yveltal;
        public static Pokemon Zygarde;
        public static Pokemon CompleteZygarde;
        public static Pokemon DogZygarde;
        public static Pokemon Diancie;
        public static Pokemon MegaDiancie;
        public static Pokemon Hoopa;
        public static Pokemon UnboundHoopa;
        public static Pokemon Volcanion;
        #endregion

        #region Alola
        public static Pokemon Rowlet;
        public static Pokemon Dartrix;
        public static Pokemon Decidueye;
        public static Pokemon Litten;
        public static Pokemon Torracat;
        public static Pokemon Incineroar;
        public static Pokemon Popplio;
        public static Pokemon Brionne;
        public static Pokemon Primarina;
        public static Pokemon Pikipek;
        public static Pokemon Trumbeak;
        public static Pokemon Toucannon;
        public static Pokemon Yungoos;
        public static Pokemon Gumshoos;
        public static Pokemon Grubbin;
        public static Pokemon Charjabug;
        public static Pokemon Vikavolt;
        public static Pokemon Crabrawler;
        public static Pokemon Crabominable;
        public static Pokemon PauOricorio;
        public static Pokemon SensuOricorio;
        public static Pokemon PomPomOricorio;
        public static Pokemon Cutiefly;
        public static Pokemon Ribombee;
        public static Pokemon Rockruff;
        public static Pokemon MiddayLycanroc;
        public static Pokemon MidnightLycanroc;
        public static Pokemon SoloWishiwashi;
        public static Pokemon SchoolWishiwashi;
        public static Pokemon Mareanie;
        public static Pokemon Toxapex;
        public static Pokemon Mudbray;
        public static Pokemon Mudsdale;
        public static Pokemon Dewpider;
        public static Pokemon Araquanid;
        public static Pokemon Fomantis;
        public static Pokemon Lurantis;
        public static Pokemon Morelull;
        public static Pokemon Shiinotic;
        public static Pokemon Salandit;
        public static Pokemon Salazzle;
        public static Pokemon Stufful;
        public static Pokemon Bewear;
        public static Pokemon Bounsweet;
        public static Pokemon Stenee;
        public static Pokemon Tsareena;
        public static Pokemon Comfey;
        public static Pokemon Oranguru;
        public static Pokemon Passimian;
        public static Pokemon Wimpod;
        public static Pokemon Golisopod;
        public static Pokemon Sandygast;
        public static Pokemon Palossand;
        public static Pokemon Pyukumuku;
        public static Pokemon TypeNull;
        public static Pokemon Silvally;
        public static Pokemon MeteorMinior;
        public static Pokemon CoreMinior;
        public static Pokemon Komala;
        public static Pokemon Turtonator;
        public static Pokemon Togedemaru;
        public static Pokemon Mimikyu;
        public static Pokemon Bruxish;
        public static Pokemon Drampa;
        public static Pokemon Dhelmise;
        public static Pokemon Jangmoo;
        public static Pokemon Hakamoo;
        public static Pokemon Kommoo;
        public static Pokemon TapuKoko;
        public static Pokemon TapuLele;
        public static Pokemon TapuBulu;
        public static Pokemon TapuFini;
        public static Pokemon Cosmog;
        public static Pokemon Cosmoem;
        public static Pokemon Solgaleo;
        public static Pokemon Lunala;
        public static Pokemon Nihilego;
        public static Pokemon Buzzwole;
        public static Pokemon Pheromosa;
        public static Pokemon Xurkitree;
        public static Pokemon Celesteela;
        public static Pokemon Kartana;
        public static Pokemon Guzzlord;
        public static Pokemon Necrozma;
        public static Pokemon Magearna;
        public static Pokemon Marshadow;
        #endregion

        #endregion

        #region Definitions
        static Pkmn()
        {
            Bulbasaur = new Pokemon(1, "Bulbasaur", "Bulbasaur can be seen napping in bright sunlight. There is a seed on its back. By soaking up the sun’s rays, the seed grows progressively larger.", Type.Grass, Type.Poison, new Ability[] { Abilities.Overgrow, Abilities.Chlorophyll }, new double[] { 45, 49, 49, 65, 65, 45, 70, 15.2 }, new Move[] { Moves.Normal.Tackle, Moves.Normal.Growl, Moves.Grass.VineWhip, Moves.Poison.PoisonPowder, Moves.Grass.SleepPowder, Moves.Normal.TakeDown, Moves.Grass.RazorLeaf, Moves.Normal.SweetScent, Moves.Normal.Growth, Moves.Normal.DoubleEdge, Moves.Grass.WorrySeed, Moves.Grass.Synthesis, Moves.Grass.SeedBomb, Moves.Psychic.Amnesia, Moves.Fairy.Charm, Moves.Ghost.NonGhostCurse, Moves.Normal.Endure, Moves.Grass.GigaDrain, Moves.Grass.GrassWhistle, Moves.Grass.GrassyTerrain, Moves.Grass.Ingrain, Moves.Grass.LeafStorm, Moves.Grass.MagicalLeaf, Moves.Normal.NaturePower, Moves.Grass.PetalDance, Moves.Grass.PowerWhip, Moves.Normal.SkullBash, Moves.Poison.Sludge, Moves.Grass.FrenzyPlant, Moves.Normal.WorkUp, Moves.Poison.Toxic, Moves.Poison.Venoshock, Moves.Normal.HiddenPower, Moves.Fire.SunnyDay, Moves.Psychic.LightScreen, Moves.Normal.Protect, Moves.Normal.Safeguard, Moves.Normal.Frustration, Moves.Grass.SolarBeam, Moves.Normal.Return, Moves.Normal.DoubleTeam, Moves.Poison.SludgeBomb, Moves.Normal.Facade, Moves.Psychic.Rest, Moves.Normal.Attract, Moves.Normal.Round, Moves.Normal.EchoedVoice, Moves.Grass.EnergyBall, Moves.Normal.SwordsDance, Moves.Grass.GrassKnot, Moves.Normal.Swagger, Moves.Normal.SleepTalk, Moves.Normal.Substitute, Moves.Normal.NaturePower, Moves.Normal.Confide });
            Ivysaur = new Pokemon(2, "Ivysaur", "There is a bud on this Pokémon’s back. To support its weight, Ivysaur’s legs and trunk grow thick and strong. If it starts spending more time lying in the sunlight, it’s a sign that the bud will bloom into a large flower soon.", Type.Grass, Type.Poison, new Ability[] { Abilities.Overgrow, Abilities.Chlorophyll }, new double[] { 60, 62, 63, 80, 80, 60, 70, 28.7 }, new Move[] { Moves.Normal.Growl, Moves.Normal.Tackle, Moves.Grass.LeechSeed, Moves.Grass.VineWhip, Moves.Poison.PoisonPowder, Moves.Grass.SleepPowder, Moves.Normal.TakeDown, Moves.Grass.RazorLeaf, Moves.Normal.SweetScent, Moves.Normal.Growth, Moves.Normal.DoubleEdge, Moves.Grass.WorrySeed, Moves.Grass.Synthesis, Moves.Grass.SolarBeam , Moves.Psychic.Amnesia, Moves.Fairy.Charm, Moves.Ghost.NonGhostCurse, Moves.Normal.Endure, Moves.Grass.GigaDrain, Moves.Grass.GrassWhistle, Moves.Grass.GrassyTerrain, Moves.Grass.Ingrain, Moves.Grass.LeafStorm, Moves.Grass.MagicalLeaf, Moves.Normal.NaturePower, Moves.Grass.PetalDance, Moves.Grass.PowerWhip, Moves.Normal.SkullBash, Moves.Poison.Sludge, Moves.Grass.FrenzyPlant, Moves.Normal.WorkUp, Moves.Poison.Toxic, Moves.Poison.Venoshock, Moves.Normal.HiddenPower, Moves.Fire.SunnyDay, Moves.Psychic.LightScreen, Moves.Normal.Protect, Moves.Normal.Safeguard, Moves.Normal.Frustration, Moves.Grass.SolarBeam, Moves.Normal.Return, Moves.Normal.DoubleTeam, Moves.Poison.SludgeBomb, Moves.Normal.Facade, Moves.Psychic.Rest, Moves.Normal.Attract, Moves.Normal.Round, Moves.Normal.EchoedVoice, Moves.Grass.EnergyBall, Moves.Normal.SwordsDance, Moves.Grass.GrassKnot, Moves.Normal.Swagger, Moves.Normal.SleepTalk, Moves.Normal.Substitute, Moves.Normal.NaturePower, Moves.Normal.Confide} );
            Venusaur = new Pokemon(3, "Venusaur", "There is a large flower on Venusaur’s back. The flower is said to take on vivid colors if it gets plenty of nutrition and sunlight. The flower’s aroma soothes the emotions of people.", Type.Grass, Type.Poison, new Ability[] { Abilities.Overgrow, Abilities.Chlorophyll }, new double[] { 80, 82, 83, 100, 100, 80, 70, 220.5 }, new Move[] { Moves.Normal.Growl, Moves.Grass.PetalDance, Moves.Normal.Tackle, Moves.Grass.VineWhip, Moves.Grass.LeechSeed, Moves.Poison.PoisonPowder, Moves.Grass.SleepPowder, Moves.Normal.TakeDown, Moves.Grass.RazorLeaf, Moves.Normal.SweetScent, Moves.Normal.Growth, Moves.Normal.DoubleEdge, Moves.Grass.WorrySeed, Moves.Grass.Synthesis, Moves.Grass.PetalBLizzard, Moves.Grass.SolarBeam, Moves.Grass.PetalDance, Moves.Psychic.Amnesia, Moves.Fairy.Charm, Moves.Ghost.NonGhostCurse, Moves.Normal.Endure, Moves.Grass.GigaDrain, Moves.Grass.GrassWhistle, Moves.Grass.GrassyTerrain, Moves.Grass.Ingrain, Moves.Grass.LeafStorm, Moves.Grass.MagicalLeaf, Moves.Normal.NaturePower, Moves.Grass.PowerWhip, Moves.Normal.SkullBash, Moves.Poison.Sludge, Moves.Grass.FrenzyPlant, Moves.Grass.GrassPledge, Moves.Normal.WorkUp, Moves.Normal.Roar, Moves.Poison.Toxic, Moves.Poison.Venoshock, Moves.Normal.HiddenPower, Moves.Fire.SunnyDay, Moves.Normal.HyperBeam, Moves.Psychic.LightScreen, Moves.Normal.Protect, Moves.Normal.Safeguard, Moves.Normal.Frustration, Moves.Grass.SolarBeam, Moves.Ground.Earthquake, Moves.Normal.Return, Moves.Normal.DoubleTeam, Moves.Poison.SludgeBomb, Moves.Normal.Facade, Moves.Psychic.Rest, Moves.Normal.Attract, Moves.Normal.Round, Moves.Normal.EchoedVoice, Moves.Grass.EnergyBall, Moves.Normal.GigaImpact, Moves.Normal.SwordsDance, Moves.Ground.Bulldoze, Moves.Grass.GrassKnot, Moves.Normal.Swagger, Moves.Normal.SleepTalk, Moves.Normal.Substitute, Moves.Normal.NaturePower, Moves.Normal.Confide });
            MegaVenusaur = new Pokemon(3, "Venusaur", "There is a large flower on Venusaur’s back. The flower is said to take on vivid colors if it gets plenty of nutrition and sunlight. The flower’s aroma soothes the emotions of people.", Type.Grass, Type.Poison, new Ability[] { Abilities.ThickFat }, new double[] { 80, 100, 123, 122, 120, 80, 70, 342.8 }, new Move[] { Moves.Normal.Growl, Moves.Grass.PetalDance, Moves.Normal.Tackle, Moves.Grass.VineWhip, Moves.Grass.LeechSeed, Moves.Poison.PoisonPowder, Moves.Grass.SleepPowder, Moves.Normal.TakeDown, Moves.Grass.RazorLeaf, Moves.Normal.SweetScent, Moves.Normal.Growth, Moves.Normal.DoubleEdge, Moves.Grass.WorrySeed, Moves.Grass.Synthesis, Moves.Grass.PetalBLizzard, Moves.Grass.SolarBeam, Moves.Grass.PetalDance, Moves.Psychic.Amnesia, Moves.Fairy.Charm, Moves.Ghost.NonGhostCurse, Moves.Normal.Endure, Moves.Grass.GigaDrain, Moves.Grass.GrassWhistle, Moves.Grass.GrassyTerrain, Moves.Grass.Ingrain, Moves.Grass.LeafStorm, Moves.Grass.MagicalLeaf, Moves.Normal.NaturePower, Moves.Grass.PowerWhip, Moves.Normal.SkullBash, Moves.Poison.Sludge, Moves.Grass.FrenzyPlant, Moves.Grass.GrassPledge, Moves.Normal.WorkUp, Moves.Normal.Roar, Moves.Poison.Toxic, Moves.Poison.Venoshock, Moves.Normal.HiddenPower, Moves.Fire.SunnyDay, Moves.Normal.HyperBeam, Moves.Psychic.LightScreen, Moves.Normal.Protect, Moves.Normal.Safeguard, Moves.Normal.Frustration, Moves.Grass.SolarBeam, Moves.Ground.Earthquake, Moves.Normal.Return, Moves.Normal.DoubleTeam, Moves.Poison.SludgeBomb, Moves.Normal.Facade, Moves.Psychic.Rest, Moves.Normal.Attract, Moves.Normal.Round, Moves.Normal.EchoedVoice, Moves.Grass.EnergyBall, Moves.Normal.GigaImpact, Moves.Normal.SwordsDance, Moves.Ground.Bulldoze, Moves.Grass.GrassKnot, Moves.Normal.Swagger, Moves.Normal.SleepTalk, Moves.Normal.Substitute, Moves.Normal.NaturePower, Moves.Normal.Confide });
            Charmander = new Pokemon(4, "Charmander", "The flame that burns at the tip of its tail is an indication of its emotions. The flame wavers when Charmander is enjoying itself. If the Pokémon becomes enraged, the flame burns fiercely.", Type.Fire, Type.Typeless, new Ability[] { Abilities.Blaze, Abilities.SolarPower }, new double[] { 39, 52, 43, 60, 50, 65, 70, 18.7 }, new Move[] { Moves.Normal.Growl, Moves.Normal.Scratch, Moves.Fire.Ember, Moves.Normal.Smokescreen, Moves.Dragon.DragonRage, Moves.Normal.ScaryFace, Moves.Fire.FireFang, Moves.Fire.FireBlast, Moves.Normal.Slash, Moves.Fire.Flamethrower, Moves.Fire.FireSpin, Moves.Fire.Inferno, Moves.Flying.AirCutter, Moves.Rock.AncientPower, Moves.Dark.BeatUp, Moves.Normal.BellyDrum, Moves.Dark.Bite, Moves.Fighting.Counter, Moves.Dark.Crunch, Moves.Dragon.DragonDance, Moves.Dragon.DragonPulse, Moves.Dragon.DragonRush, Moves.Fire.FlareBlitz, Moves.Fighting.FocusPunch, Moves.Steel.MetalClaw, Moves.Dragon.Outrage, Moves.Normal.WorkUp, Moves.Dragon.DragonClaw, Moves.Poison.Toxic, Moves.Normal.HiddenPower, Moves.Fire.SunnyDay, Moves.Normal.Protect, Moves.Normal.Frustration, Moves.Normal.Return, Moves.Fighting.BrickBreak, Moves.Normal.DoubleTeam, Moves.Fire.BlastBurn, Moves.Fire.FireBlast, Moves.Rock.RockTOmb, Moves.Flying.AerialAce, Moves.Normal.Facade, Moves.Fire.FlameCharge, Moves.Psychic.Rest, Moves.Normal.Attract, Moves.Normal.Round, Moves.Normal.EchoedVoice, Moves.Fire.Overheat, Moves.Dark.Fling, Moves.Fire.WillOWisp, Moves.Ghost.ShadowClaw, Moves.Normal.SwordsDance, Moves.Rock.RockSlide, Moves.Normal.Swagger, Moves.Normal.SleepTalk, Moves.Normal.Substitute, Moves.Normal.Confide });

        }
        #endregion
    }
}
